Log:
  Level: info

ExternalSecure: true
ExternalDomain: eloauth.com
ExternalPort: 443

Database:
  cockroach:
    Port: 26257
    Database: zitadel
    MaxOpenConns: 20
    MaxConnLifetime: 30m
    MaxConnIdleTime: 30m
    Options: ""
    User:
      SSL:
        Mode: require
    Admin:
      SSL:
        Mode: require
